# Generated by Django 4.2.7 on 2024-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_remove_kaizenuser_department_kaizenuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kaizenuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
